# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
- changed-files:
  - any-glob-to-any-file: '*'

# Add 'documentation' label to any change to .md files within the entire repository
documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

# Add 'action' label to any change to the composite action definition
action:
- changed-files:
  - any-glob-to-any-file: 'action.yml'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature', 'feat', '^feat']

bug:
 - head-branch: ['^fix', 'fix', '^bug', 'bug', '^issue', 'issue']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

# Add 'ci-cd' label to any change to the GitHub Actions workflows
ci-cd:
 - changed-files:
   - any-glob-to-any-file: '.github/.workflows/**'

# Add 'dependencies' label to any change to project dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'uv.lock']

# Add 'tooling' label to any change to dev tooling config
tooling:
  - changed-files:
    - any-glob-to-any-file: ['.pre-commit-config.yaml', '.editorconfig']
