name: 'Check Markdown'
description: 'Return errors found on a pull request with problems in .md and .ipynb files.'
author: "John Aziz"
branding:
  color: "green"
  icon: "check-circle"

inputs:
  command:
    description: The function to run and validate.
    required: true
    default: check-broken-paths
  directory:
    description: The directory that contains .md and .ipynb files.
    required: true
    default: ./
  github-token:
    description: GitHub token
    required: true
    default: ''

outputs:
  is-valid:
    description: "Validation run status"
    value: ${{ steps.update-status.outputs.isValid }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
      shell: bash
    - name: Run Check broken paths
      if:  ${{ inputs.command == 'check-broken-paths' }}
      run: |
        BROKEN_PATHS=$(python ./main.py --dir ${{ inputs.directory }} --func 'check_broken_paths')
        echo "BROKEN_PATHS<<EOF" >> $GITHUB_ENV
        echo "$BROKEN_PATHS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Run Check paths tracking
      if:  ${{ inputs.command == 'check-paths-tracking' }}
      run: |
        PATHS_TRACKING=$(python ./main.py --dir ${{ inputs.directory }} --func 'check_paths_tracking')
        echo "PATHS_TRACKING<<EOF" >> $GITHUB_ENV
        echo "$PATHS_TRACKING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Run Check URLs tracking
      if:  ${{ inputs.command == 'check-urls-tracking' }}
      run: |
        URLS_TRACKING=$(python ./main.py --dir ${{ inputs.directory }} --func 'check_urls_tracking')
        echo "URLS_TRACKING<<EOF" >> $GITHUB_ENV
        echo "$URLS_TRACKING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Run Check URLs Country Locale
      if:  ${{ inputs.command == 'check-urls-locale' }}
      run: |
        URLS_LOCALE=$(python ./main.py --dir ${{ inputs.directory }} --func 'check_urls_locale')
        echo "URLS_LOCALE<<EOF" >> $GITHUB_ENV
        echo "$URLS_LOCALE" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

   - name: Update workflow run status
     id: update-status
     if:  ${{  env.BROKEN_PATHS != '' ||  env.PATHS_TRACKING != '' || env.URLS_TRACKING != '' ||  env.URLS_LOCALE != ''}}
     run: echo "::set-output name=isValid::1"
     shell: bash
