name: 'Check Markdown'
description: 'Return errors found on a pull request with problems in .md and .ipynb files.'
author: "John Aziz"
branding:
  color: "green"
  icon: "check-circle"

inputs:
  command:
    description: The function to run and validate.
    required: true
    default: check-broken-paths
  directory:
    description: The directory that contains .md and .ipynb files.
    required: true
    default: ./
  guide-url:
    description: The contribution guide full URL.
    required: true
    default: 'https://github.com/john0isaac/action-check-markdown/blob/main/CONTRIBUTING.md'
  github-token:
    description: GitHub token
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install markdown-checker
      shell: bash
    - name: Run markdown-checker
      run: |
        markdown-checker --dir ${{ env.directory }} --func ${{ env.command }} --guide-url ${{ env.guide-url }}
      shell: bash

    - name: Set job summary
      if: ${{ always() &&  hashFiles('./comment.md') != '' }}
      shell: bash
      run: cat ./comment.md >> $GITHUB_STEP_SUMMARY

    - name: Post comment
      if: ${{ always() &&  hashFiles('./comment.md') != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: gh pr comment ${{ github.event.pull_request.html_url }} -F ./comment.md

    - name: Update workflow run status
      if: ${{ always() &&  hashFiles('./comment.md') != '' }}
      run: exit 1
